const results = [
  { number: 0, colour: "green", parity: null },
  { number: 1, colour: "red", parity: false },
  { number: 2, colour: "black", parity: true },
  { number: 3, colour: "red", parity: false },
  { number: 4, colour: "black", parity: true },
  { number: 5, colour: "red", parity: false },
  { number: 6, colour: "black", parity: true },
  { number: 7, colour: "red", parity: false },
  { number: 8, colour: "black", parity: true },
  { number: 9, colour: "red", parity: false },
  { number: 10, colour: "black", parity: true },
  { number: 11, colour: "black", parity: false },
  { number: 12, colour: "red", parity: true },
  { number: 13, colour: "black", parity: false },
  { number: 14, colour: "red", parity: true },
  { number: 15, colour: "black", parity: false },
  { number: 16, colour: "red", parity: true },
  { number: 17, colour: "black", parity: false },
  { number: 18, colour: "red", parity: true },
  { number: 19, colour: "red", parity: false },
  { number: 20, colour: "black", parity: true },
  { number: 21, colour: "red", parity: false },
  { number: 22, colour: "black", parity: true },
  { number: 23, colour: "red", parity: false },
  { number: 24, colour: "black", parity: true },
  { number: 25, colour: "red", parity: false },
  { number: 26, colour: "black", parity: true },
  { number: 27, colour: "red", parity: false },
  { number: 28, colour: "black", parity: true },
  { number: 29, colour: "black", parity: false },
  { number: 30, colour: "red", parity: true },
  { number: 31, colour: "black", parity: false },
  { number: 32, colour: "red", parity: true },
  { number: 33, colour: "black", parity: false },
  { number: 34, colour: "red", parity: true },
  { number: 35, colour: "black", parity: false },
  { number: 36, colour: "red", parity: true },
];

module.exports = results;
